"""add zipcode

Revision ID: 323f7895d8a7
Revises: ddde4f2eb8f3
Create Date: 2026-01-13 11:20:50.520437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '323f7895d8a7'
down_revision: Union[str, Sequence[str], None] = 'ddde4f2eb8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zipcode', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zipcode')
    # ### end Alembic commands ###
