"""add house_no

Revision ID: a519c9dc3d12
Revises: 323f7895d8a7
Create Date: 2026-01-13 11:54:45.834264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a519c9dc3d12'
down_revision: Union[str, Sequence[str], None] = '323f7895d8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('house_no', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'house_no')
    # ### end Alembic commands ###
